Ejercicio LINUX
a10pepo/EDEM_MDA2425 pull request #205
Opened 2024-10-09 11:20 UTC by e-wach

Carpeta LINUX + README.md

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [X] He probado mi código y funciona en local
- [X] He validado que mi código es correcto a niveles de formato
- [X] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [X] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P
![JKqrh7](https://github.com/user-attachments/assets/5e507fd6-1780-4f9d-afd2-b6eb3bb62cea)

2024-10-10 13:23 UTC, a10pepo requested changes

2024-10-10 13:23 UTC, a10pepo commented on ALUMNOS/MDAB/TING_WANG/LINUX/README.md
> +    ls -al
directorio raiz???

2024-10-10 13:23 UTC, a10pepo commented on ALUMNOS/MDAB/TING_WANG/LINUX/README.md
> +  ./script.sh
Aquí me refería a:

ls /tmp/PRUEBA/*

2024-10-14 15:11 UTC, e-wach commented
se me olvidó darle a "re-review" :')

2024-10-14 17:33 UTC, a10pepo approved these changes

2024-10-14 17:33 UTC, a10pepo commented on ALUMNOS/MDAB/TING_WANG/LINUX/README.md
> +    No existe motd ? Es mtab?
Valian las dos 😉

2024-10-14 17:33 UTC, merged