Ejercicio LINUX
a10pepo/EDEM_MDA2425 pull request #211
Opened 2024-10-10 12:17 UTC by eabadz

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [x] He probado mi código y funciona en local
- [x] He validado que mi código es correcto a niveles de formato
- [x] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [x] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2024-10-10 13:02 UTC, pedronieto1206 requested changes

2024-10-10 13:02 UTC, pedronieto1206 commented on ALUMNOS/MIA/Eduardo_Abad/LINUX/README.md
> +  root@76e0c2c4ed1d:/tmp/PRUEBA# rm -rR
seguro que -rR es así?

2024-10-13 14:48 UTC, a10pepo requested changes

2024-10-14 10:39 UTC, eabadz commented on ALUMNOS/MIA/Eduardo_Abad/LINUX/README.md
> +  root@76e0c2c4ed1d:/dev# ls tty* *3
Ahora lo he cambiado pero aun así poner que no existe ningún archivo para estos requisitos

2024-10-14 17:32 UTC, merged