jobarbru_LINUX
a10pepo/EDEM_MDA2425 pull request #214
Opened 2024-10-10 15:52 UTC by Jobarbru

Resolución ejercicio LINUX

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2024-10-13 14:43 UTC, a10pepo requested changes

2024-10-13 14:43 UTC, a10pepo commented on ALUMNOS/MIA/JOSE_BARBERO/LINUX/LINUX.md
> +    16. rm -r
Aqui solo funcionara si estas en el directorio correcto no?

2024-10-14 09:34 UTC, Jobarbru commented on ALUMNOS/MIA/JOSE_BARBERO/LINUX/LINUX.md
> +    16. rm -r
Si, lo hice así suponiendo que estábamos en el directorio HOME

2024-10-17 05:58 UTC, a10pepo approved these changes

2024-10-17 05:58 UTC, merged