Entrega Linux Marta
a10pepo/EDEM_MDA2425 pull request #217
Opened 2024-10-10 16:15 UTC by martamiro

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ x] He probado mi código y funciona en local
- [ x] He validado que mi código es correcto a niveles de formato
- [x ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ x] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2024-10-13 14:41 UTC, a10pepo requested changes

2024-10-13 14:41 UTC, a10pepo commented on ALUMNOS/MDAA/MARTA_MIRO/LINUX/ScriptLinuxMarta.sh
> +chmod 777
Esto cambia permisos no muestra...

2024-10-13 14:41 UTC, a10pepo commented on ALUMNOS/MDAA/MARTA_MIRO/LINUX/ScriptLinuxMarta.sh
> +chmod 777 ScriptLinuxMarta.sh
¿Xq esta esto aquí?

2024-10-14 14:35 UTC, martamiro commented
Hola Pedro, después de hacer commit+push con los cambios no me sale la opción de abrir otra PR. Puedes revisar si te han llegado los cambios? Muchas gracias, Marta

2024-10-14 14:36 UTC, martamiro commented on ALUMNOS/MDAA/MARTA_MIRO/LINUX/ScriptLinuxMarta.sh
> +chmod 777 ScriptLinuxMarta.sh
#20.Comprobar el ejercicio anterior mediante un solo comando.
ls -R /tmp/PRUEBA

2024-10-14 14:36 UTC, martamiro commented on ALUMNOS/MDAA/MARTA_MIRO/LINUX/ScriptLinuxMarta.sh
> +chmod 777
#15.Listar todos los ficheros del directorio HOME mostrando sus permisos.
cd ls -l

2024-10-14 17:35 UTC, merged