ejercicio_linux
a10pepo/EDEM_MDA2425 pull request #237
Opened 2024-10-13 15:31 UTC by parnaullo

subo entregable linux

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [x ] He probado mi código y funciona en local
- [x ] He validado que mi código es correcto a niveles de formato
- [x ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [x ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2024-10-13 17:02 UTC, a10pepo requested changes

2024-10-13 17:02 UTC, a10pepo commented on ALUMNOS/MIA/PABLO_ARNAU/LINUX/README.md
> +ls -l | grep t*
Has probado esto? Prueba en un solo comando

2024-10-13 17:02 UTC, a10pepo commented on ALUMNOS/MIA/PABLO_ARNAU/LINUX/README.md
> +ls | grep tty*
Lo mismo q el anterior usa un argumento con comodin en el ls

2024-10-13 17:02 UTC, a10pepo commented on ALUMNOS/MIA/PABLO_ARNAU/LINUX/README.md
> +ls- /home
Estas seguro?

2024-10-14 15:43 UTC, parnaullo commented on ALUMNOS/MIA/PABLO_ARNAU/LINUX/README.md
> +ls- /home
Me faltaba el argumento comodín, he modificado el nombre del directorio. Cogí un directorio home que había dentro de la raíz que se llamaba home

2024-10-14 15:49 UTC, parnaullo commented on ALUMNOS/MIA/PABLO_ARNAU/LINUX/README.md
> +ls -l | grep t*
Modificado a un solo comando

2024-10-14 15:50 UTC, parnaullo commented on ALUMNOS/MIA/PABLO_ARNAU/LINUX/README.md
> +ls | grep tty*
Modificado a un solo comando y añado comodín.

2024-10-14 16:20 UTC, merged