Veintimilla docker
a10pepo/EDEM_MDA2425 pull request #394
Opened 2024-12-02 10:36 UTC by VeintimillAlejandro

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [x] He probado mi código y funciona en local
- [x] He validado que mi código es correcto a niveles de formato
- [x] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [x] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2024-12-03 09:33 UTC, martinImagina commented on ALUMNOS/MIA/ALEJANDRO_VEINTIMILLA/PYTHON/Curso de Python/Sesión 1/Ejercicio 2/main.py
¡ok!

2024-12-03 09:34 UTC, martinImagina commented on ALUMNOS/MIA/ALEJANDRO_VEINTIMILLA/PYTHON/Curso de Python/Sesión 2/main.py
Bien, pero sería recomendable el uso de try...except para evitar errores a la hora de convertir a int o a float entradas por consola del usuario. Así protegerías tu código de errores de ejecución si el usuario no intruduce lo que esperas que introduzca y capturas el error para evitar que el programa termine bajo éste.

2024-12-03 09:35 UTC, martinImagina commented on ALUMNOS/MIA/ALEJANDRO_VEINTIMILLA/PYTHON/Curso de Python/Sesión 3/Ejercicio 1/main.py
Bien, pero como en el anterior, sería recomendable el uso de try...except para evitar errores a la hora de convertir a int o a float entradas por consola del usuario.

2024-12-03 09:35 UTC, martinImagina commented on ALUMNOS/MIA/ALEJANDRO_VEINTIMILLA/PYTHON/Curso de Python/Sesión 3/Ejercicio 2/main.py
¡ok!

2024-12-03 09:35 UTC, martinImagina commented on ALUMNOS/MIA/ALEJANDRO_VEINTIMILLA/PYTHON/Curso de Python/Sesión 3/Ejercicio 3/main.py
¡ok!

2024-12-03 09:36 UTC, martinImagina commented on ALUMNOS/MIA/ALEJANDRO_VEINTIMILLA/PYTHON/Curso de Python/Sesión 4/Ejercicio 2/main.py
Pendiente

2024-12-03 09:37 UTC, martinImagina commented on ALUMNOS/MIA/ALEJANDRO_VEINTIMILLA/PYTHON/Curso de Python/Sesión 4/Ejercicio 3/main.py
Bien, pero sería recomendable el uso de try...except para evitar errores a la hora acceder a claves del JSON que puede que no llegasen al recibir la respuesta de la petición HTTPs.

2024-12-03 09:37 UTC, martinImagina commented on ALUMNOS/MIA/ALEJANDRO_VEINTIMILLA/PYTHON/Curso de Python/Sesión 5/Ejercicio 1/main.py
Pendiente

2024-12-03 09:37 UTC, martinImagina commented on ALUMNOS/MIA/ALEJANDRO_VEINTIMILLA/PYTHON/Curso de Python/Sesión 5/Ejercicio 2/main.py
¡ok!

2024-12-03 09:37 UTC, martinImagina commented on ALUMNOS/MIA/ALEJANDRO_VEINTIMILLA/PYTHON/Curso de Python/Sesión 5/Ejercicio 3/main.py
¡ok!

2024-12-03 09:39 UTC, martinImagina requested changes
Me temo que me has incluido en la aprobación de entregas que corresponden al profe de Docker.

Por mi parte te he dejado ok en los ejercicios de Python que estaban bien y algún comentario/recomendación en los que podrías haber añadido algo más de protección a tu código. También te he indicado que algunos están vacíos y estarían pendientes :)

Habla con @a10pepo para modificar la pull request para que la parte de Docker entregada no dependa de mi aprobación y solo sean las entregas de python. 

¡Un saludo!

2025-01-13 14:58 UTC, MA-Barracas reviewed
Yo, mi parte de docker la veo bien, pero menuda fiesta de PR!

2025-01-13 15:41 UTC, VeintimillAlejandro commented
> Yo, mi parte de docker la veo bien, pero menuda fiesta de PR!

Yo lo llamo pesadilla

2025-01-13 16:33 UTC, merged