DBT ejercicios
a10pepo/EDEM_MDA2425 pull request #400
Opened 2024-12-02 18:58 UTC by raulalgora

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2024-12-03 09:30 UTC, martinImagina requested changes
Me temo que me has incluido en el proceso de aprobación, pero este ejercicio parece ser para el instructor de SQL.

Puedes hablar con @a10pepo para que te indique cómo cambiar la Pull request y que no requiera de mi aprobación, ya que yo solo me centraré en las entregas de Python :)

2024-12-03 11:35 UTC, a10pepo commented
Necesitas hacerlo en tu carpeta, no en profesores!!!

2024-12-03 11:35 UTC, a10pepo requested changes
Muevelo a tu carpeta

2024-12-20 15:16 UTC, Rosalln approved these changes

2025-01-03 09:10 UTC, a10pepo approved these changes

2025-01-03 09:10 UTC, merged