Ejercicio-DBT-joel1091
a10pepo/EDEM_MDA2425 pull request #401
Opened 2024-12-02 22:16 UTC by joel1091

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2024-12-03 09:29 UTC, martinImagina requested changes
Me temo que me has incluido en el proceso de aprobación, pero este ejercicio parece ser para el instructor de SQL o DBT.

Puedes hablar con @a10pepo para que te indique cómo cambiar la Pull request y que no requiera de mi aprobación, ya que yo solo me centraré en las entregas de Python :)

2024-12-03 10:13 UTC, joel1091 commented
> Me temo que me has incluido en el proceso de aprobación, pero este ejercicio parece ser para el instructor de SQL o DBT.
> 
> Puedes hablar con @a10pepo para que te indique cómo cambiar la Pull request y que no requiera de mi aprobación, ya que yo solo me centraré en las entregas de Python :)

Buenas!
No te puse en el proceso de selección, creo que estás teniendo un problema y estas recibiendo algún tipo de correo de confirmación, ya que estas respondiendo todos los commits de mis compañeros y tampoco te han etiquetado.

Un saludo

2024-12-03 10:14 UTC, joel1091 commented
![Screenshot_2024-12-03-11-14-20-879_com.github.android.jpg](https://github.com/user-attachments/assets/2a9555e0-1074-46a0-b103-8d08722d9670)

2024-12-03 10:39 UTC, martinImagina commented
@a10pepo si puedes revisar cómo está organizado el repo o cómo se están gestionando las Pull Requests, te lo agradezco.

![image](https://github.com/user-attachments/assets/23008c79-8621-42c5-8e9e-41cf5ad193f1)

![image](https://github.com/user-attachments/assets/21615ed0-11e3-45a3-80d0-9f5a7d0b2acd)

Me estarían llegando solicitudes de revisión de Docker, SQL, DBT, etc.

2024-12-03 13:27 UTC, a10pepo commented
> @a10pepo si puedes revisar cómo está organizado el repo o cómo se están gestionando las Pull Requests, te lo agradezco.
> 
> ![image](https://private-user-images.githubusercontent.com/41681622/391928501-23008c79-8621-42c5-8e9e-41cf5ad193f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzI2NTAsIm5iZiI6MTczMzIzMjM1MCwicGF0aCI6Ii80MTY4MTYyMi8zOTE5Mjg1MDEtMjMwMDhjNzktODYyMS00MmM1LThlOWUtNDFjZjVhZDE5M2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDEzMjU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNjIxNjI1NmNjMzU2YjQ1N2RhNGRiMjBlNGMwZTgyM2I5YTdjMjM1Nzg5N2JhZmRlNmYyZTJlZDVkMTBhNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lPtxc-E7X1D4r32vDx1Lqtge8nWZz6Rb2cKLGwvOKqs)
> 
> ![image](https://private-user-images.githubusercontent.com/41681622/391928620-21615ed0-11e3-45a3-80d0-9f5a7d0b2acd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzI2NTAsIm5iZiI6MTczMzIzMjM1MCwicGF0aCI6Ii80MTY4MTYyMi8zOTE5Mjg2MjAtMjE2MTVlZDAtMTFlMy00NWEzLTgwZDAtOWY1YTdkMGIyYWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDEzMjU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxYmY4NTE4YzhmYWQ4YjNmMDAxNzMzYjkwNGQwYWZlY2MxODdhNDg1OGRkMDFjNzFjYzJiYzhlYmZjMjc5YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JO-S3bOoqwzOF_FcbK0gLA6tPnnc-SMFzuZbdKiLHiU)
> 
> Me estarían llegando solicitudes de revisión de Docker, SQL, DBT, etc.



> @a10pepo si puedes revisar cómo está organizado el repo o cómo se están gestionando las Pull Requests, te lo agradezco.
> 
> ![image](https://private-user-images.githubusercontent.com/41681622/391928501-23008c79-8621-42c5-8e9e-41cf5ad193f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzI2NTAsIm5iZiI6MTczMzIzMjM1MCwicGF0aCI6Ii80MTY4MTYyMi8zOTE5Mjg1MDEtMjMwMDhjNzktODYyMS00MmM1LThlOWUtNDFjZjVhZDE5M2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDEzMjU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNjIxNjI1NmNjMzU2YjQ1N2RhNGRiMjBlNGMwZTgyM2I5YTdjMjM1Nzg5N2JhZmRlNmYyZTJlZDVkMTBhNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lPtxc-E7X1D4r32vDx1Lqtge8nWZz6Rb2cKLGwvOKqs)
> 
> ![image](https://private-user-images.githubusercontent.com/41681622/391928620-21615ed0-11e3-45a3-80d0-9f5a7d0b2acd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzI2NTAsIm5iZiI6MTczMzIzMjM1MCwicGF0aCI6Ii80MTY4MTYyMi8zOTE5Mjg2MjAtMjE2MTVlZDAtMTFlMy00NWEzLTgwZDAtOWY1YTdkMGIyYWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDEzMjU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxYmY4NTE4YzhmYWQ4YjNmMDAxNzMzYjkwNGQwYWZlY2MxODdhNDg1OGRkMDFjNzFjYzJiYzhlYmZjMjc5YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JO-S3bOoqwzOF_FcbK0gLA6tPnnc-SMFzuZbdKiLHiU)
> 
> Me estarían llegando solicitudes de revisión de Docker, SQL, DBT, etc.

No Martin, te están saliendo en la lista porque el repo es compartido pero como bien muestra @joel1091  no estás en los request, por lo que no te deberían llegar.

2024-12-20 15:14 UTC, Rosalln approved these changes
Te faltan los screenshoots.
En "rep_payment.." la columna "failed" sale a 0 porque el status es 'fail'

2024-12-24 12:22 UTC, joel1091 reviewed
(no hagas caso a este msg)

2025-01-29 16:57 UTC, martinImagina commented
Buenas, @joel1091 me temo que me tienes como reviewer en esta Pull Request que es sobrr DBT y se trata de un ejercicio que no te debería revisar yo.

![image](https://github.com/user-attachments/assets/528408ec-cca8-48f8-a42b-3b5194696035)

Entiendo que me tendrías que quitar como reviewer para que solo recibas la revisión. 

En mensajes anteriores @a10pepo indicaba que no me debían llegar, pero me llegan y en la captura puedes ver que se me solicita la review (lo he subrarrado en amarillo) :D

Por mi parte, si no se va a cambiar porque no haga falta, obvio el mensaje y la review pendiente, la dejo blanco y ya estaría.

Indicadme si puedo ayudar en algo.
¡Saludos!

2025-01-29 17:26 UTC, joel1091 commented
Buenas!!
Intenté eliminarte pero existe algún problema o incompatibilidad a la hora de hacerlo y volver a pedir que me acepten el pull request.

@a10pepo si puedes acepta el pull request (forzándolo), ya que Rosa me la aceptó.

Un saludo.

2025-01-29 17:34 UTC, a10pepo commented
> Buenas, @joel1091 me temo que me tienes como reviewer en esta Pull Request que es sobre DBT y se trata de un ejercicio que no te debería revisar yo.
> 
> ![image](https://private-user-images.githubusercontent.com/41681622/407828555-528408ec-cca8-48f8-a42b-3b5194696035.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgxNzIxODYsIm5iZiI6MTczODE3MTg4NiwicGF0aCI6Ii80MTY4MTYyMi80MDc4Mjg1NTUtNTI4NDA4ZWMtY2NhOC00OGY4LWE0MmItM2I1MTk0Njk2MDM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTI5VDE3MzEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZWEwZDkxMmE4NGVjMDQwMDY5NDVhOGI0NDk5MTdhYWM3ZTQyZmYxMTc2N2YxN2ZkNWJhYjBhM2FjNjQ1YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A6VIf8Gue3rTTjrlzit1xBKNdqlMivdh4za0WSs_agg)
> 
> Entiendo que me tendrías que quitar como reviewer para que solo recibas la revisión adecuada.
> 
> En mensajes anteriores @a10pepo indicaba que no me debían llegar, pero me llegan y en la captura puedes ver que se me solicita la review (lo he subrayado en amarillo) :D
> 
> Por mi parte, si no se va a cambiar porque no haga falta, obvio el mensaje y dejo la review pendiente y ya estaría.
> 
> Indicadme si puedo ayudar en algo. ¡Saludos!

Perdona @martinImagina  pero no funciona así... ya lo comenté en la PR que solicitaste cambios sin que se te asignara.

![image](https://github.com/user-attachments/assets/2c595395-1fa1-439c-90e3-d122655c6fbd)


No obstante mergeo yo. Sin problemas @joel1091

2025-01-29 17:34 UTC, merged

2025-01-29 17:50 UTC, joel1091 commented
Gracias 🙏🏾🙏🏾🙏🏾🙏🏾