PYTHON_Marc
a10pepo/EDEM_MDA2425 pull request #458
Opened 2024-12-28 13:14 UTC by Marcanta7

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2025-01-13 15:22 UTC, martinImagina commented on ALUMNOS/MDAB/MARC_CANTERO/PYTHON/ejercicio2.py
Ok, pero tienes que acordarte de proteger el código ante casting de diferentes tipos que entren por el input(...) y que luego intentes pasar a float(...) ya que podrías tener errores si el usuario no pone un número en su repsuesta por consola.

2025-01-13 15:22 UTC, martinImagina commented on ALUMNOS/MDAB/MARC_CANTERO/PYTHON/ejercicio3.py
ok. Te recomiendo lo mismo que en el ejercicio 2.

2025-01-13 15:26 UTC, martinImagina approved these changes
En la PR se me mencionaba la parte de Docker, pero que viendo a mi compañero que daba el ok, me he centrado solo en ponerte comentarios de Python :) y aprueblo pa PR.

![image](https://github.com/user-attachments/assets/c5cd1a8e-e31b-4ac8-962f-afcd080481e9)

![image](https://github.com/user-attachments/assets/5cbc5a38-4763-4d16-b7ac-421143a6edda)

Lee sobre todo los comentarios que te he puesto en el proyecto final ya que son aplicables a casi todos los ejercicios que has entregado :D

2025-01-13 16:31 UTC, a10pepo requested changes
A otra rama!

2025-01-18 08:40 UTC, pedronieto1206 approved these changes

2025-01-18 08:41 UTC, merged